

$fileID = $ARGV[0];
$classifier = $ARGV[1];

if($classifier eq "svm"){
    $file = "file_svm_".$fileID.".csv";
}
if($classifier eq "lr"){
    $file = "file_logistic".$fileID.".csv";
}
if($classifier eq "rf"){
    $file = "file_rf".$fileID.".csv";
}
$dirname = "/home/heydari/QA-System/static";
print "A,A:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'A,A' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'A,A' | sort | uniq -c |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";


print "\nA,B:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'A,B' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'A,B' | sort | uniq -c |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";

print "\nA,C:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'A,C' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'A,C' | sort | uniq -c |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";

print "\nB,A:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'B,A' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'B,A' | sort | uniq -c |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";

print "\nB,B:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'B,B' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'B,B' | sort | uniq -c  |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";

print "\nB,C:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'B,C' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'B,C' | sort | uniq -c |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";

print "\nC,A:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'C,A' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'C,A' | sort | uniq -c |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";

print "\nC,B:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'C,B' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'C,B' | sort | uniq -c |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";

print "\nC,C:";
system "cat $dirname/$file | cut -d','  -f3-4 | grep 'C,C' | wc -l";
system "cat $dirname/$file | cut -d','  -f2-4 | perl -pe 's/\-[0-9]+\.csv//g' | perl -pe 's/levelA-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelA-darse-farsi-poornamdariyan/Source2/g' | perl -pe 's/levelA-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelA-farsi-biyamuzim/Source6/g' | perl -pe 's/levelA-farsiye-omumi-saffarMoqaddam/Source4/g' | perl -pe 's/levelA-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelB-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelB-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelB-farsi-biyamuzim/Source6/g' | perl -pe 's/levelB-zabane-farsi-saffarMoqaddam/Source5/g' | perl -pe 's/levelC-amuzeshe-zabane-farsi-samare/Source1/g' | perl -pe 's/levelC-doreye-amuzeshe-zabane-farsi-zarqamiyan/Source3/g' | perl -pe 's/levelC-farsi-biyamuzim/Source6/g' | perl -pe 's/levelC-zabane-farsi-saffarMoqaddam/Source5/g' | grep 'C,C' | sort | uniq -c |  perl -pe 's/^ +| +\$//g' | perl -pe 's/ +/ /g' | awk '{print \$2\"\t\"\$1}'";
