# Generated by Django 2.1.7 on 2019-11-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField()),
                ('answers_count', models.IntegerField()),
                ('answer_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField(blank=True, null=True)),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('answer_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('answer_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('whole_text', models.TextField()),
                ('level', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QAUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedMCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.MultipleChoiceQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedVacancyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('answer_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('whole_text', models.TextField()),
                ('level', models.CharField(max_length=4)),
                ('origin_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyQuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField(blank=True, null=True)),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('answer_percentage', models.FloatField(blank=True, null=True)),
                ('questions', models.ManyToManyField(blank=True, to='language_skills.SelectedVacancyQuestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_skills.QAUser')),
            ],
        ),
        migrations.AddField(
            model_name='selectedvacancyquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.VacancyQuestion'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='options',
            field=models.ManyToManyField(blank=True, to='language_skills.OptionAnswer'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='origin_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.Text'),
        ),
        migrations.AddField(
            model_name='mcquestionset',
            name='questions',
            field=models.ManyToManyField(blank=True, to='language_skills.SelectedMCQuestion'),
        ),
        migrations.AddField(
            model_name='mcquestionset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_skills.QAUser'),
        ),
        migrations.AddField(
            model_name='mcquestionhistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.MCQuestionSet'),
        ),
    ]
