# Generated by Django 2.1.7 on 2019-12-06 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('is_verb', models.BooleanField(default=False)),
                ('is_preposition', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('whole_text', models.TextField()),
                ('level', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlankQuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField(blank=True, null=True)),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('answer_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField()),
                ('answers_count', models.IntegerField()),
                ('answer_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField(blank=True, null=True)),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('answer_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('is_verb', models.BooleanField(default=False)),
                ('is_preposition', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('whole_text', models.TextField()),
                ('level', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QAUser',
            fields=[
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=200, null=True)),
                ('native_lang', models.CharField(blank=True, max_length=200, null=True)),
                ('is_parent_persian', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('lang_reason', models.CharField(blank=True, choices=[(1, 'تحصیل دانشجوی خارجی در ایران'), (2, 'اختلال در یادگیری زبان فارسی'), (3, 'ایرانی مقیم خارج از کشور'), (4, 'علاقه شخصی')], max_length=50, null=True)),
                ('is_knowing_persian', models.BooleanField(default=False)),
                ('persian_knowing_reason', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedBlankQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.BlankQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedMCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.MultipleChoiceQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0)),
                ('question', models.ManyToManyField(to='language_skills.BlankQuestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_skills.QAUser')),
            ],
        ),
        migrations.CreateModel(
            name='VerbForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VerbInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=100)),
                ('past_root', models.CharField(max_length=100)),
                ('passive', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='verbform',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.VerbInfo'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='options',
            field=models.ManyToManyField(blank=True, to='language_skills.OptionAnswer'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='origin_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.Text'),
        ),
        migrations.AddField(
            model_name='mcquestionset',
            name='questions',
            field=models.ManyToManyField(blank=True, to='language_skills.SelectedMCQuestion'),
        ),
        migrations.AddField(
            model_name='mcquestionset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_skills.QAUser'),
        ),
        migrations.AddField(
            model_name='mcquestionhistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.MCQuestionSet'),
        ),
        migrations.AddField(
            model_name='blankquestionset',
            name='questions',
            field=models.ManyToManyField(blank=True, to='language_skills.SelectedBlankQuestion'),
        ),
        migrations.AddField(
            model_name='blankquestionset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_skills.QAUser'),
        ),
        migrations.AddField(
            model_name='blankquestion',
            name='origin_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.Text'),
        ),
    ]
