# Generated by Django 2.1.7 on 2019-10-18 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.CharField(max_length=4)),
                ('answers', models.ManyToManyField(to='language_skills.MCAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='OptionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QAUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_questions', models.ManyToManyField(blank=True, to='language_skills.MultipleChoiceQuestion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.CharField(max_length=4)),
                ('answers', models.ManyToManyField(to='language_skills.VacancyAnswer')),
                ('origin_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.Text')),
            ],
        ),
        migrations.AddField(
            model_name='qauser',
            name='v_questions',
            field=models.ManyToManyField(blank=True, to='language_skills.VacancyQuestion'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='origin_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.Text'),
        ),
        migrations.AddField(
            model_name='mcanswer',
            name='options',
            field=models.ManyToManyField(to='language_skills.OptionAnswer'),
        ),
    ]
