# Generated by Django 2.1.7 on 2019-10-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField()),
                ('answers_count', models.IntegerField()),
                ('answer_percentage', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.MultipleChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='VQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answers', models.IntegerField()),
                ('answers_count', models.IntegerField()),
                ('answer_percentage', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.VacancyQuestion')),
            ],
        ),
        migrations.RemoveField(
            model_name='mcanswer',
            name='end',
        ),
        migrations.RemoveField(
            model_name='mcanswer',
            name='start',
        ),
        migrations.RemoveField(
            model_name='vacancyanswer',
            name='end',
        ),
        migrations.RemoveField(
            model_name='vacancyanswer',
            name='start',
        ),
        migrations.AlterField(
            model_name='qauser',
            name='mc_questions',
            field=models.ManyToManyField(blank=True, to='language_skills.MCQuestionHistory'),
        ),
        migrations.AlterField(
            model_name='qauser',
            name='v_questions',
            field=models.ManyToManyField(blank=True, to='language_skills.VQuestionHistory'),
        ),
    ]
