# Generated by Django 2.1.7 on 2019-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedmcquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
