# Generated by Django 2.1.7 on 2019-12-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qauser',
            name='is_parent_persian',
        ),
        migrations.AddField(
            model_name='qauser',
            name='father_native_language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='is_father_persian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qauser',
            name='is_mother_persian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qauser',
            name='mother_native_language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
