# Generated by Django 2.1.7 on 2019-12-08 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language_skills', '0002_auto_20191207_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDetectionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_answered_blank', models.BooleanField(default=False)),
                ('has_answered_mc', models.BooleanField(default=False)),
                ('blank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_skills.SelectedBlankQuestion')),
                ('mc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_skills.SelectedMCQuestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
