# Generated by Django 2.1.7 on 2019-11-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0003_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='vacancyquestion',
            name='answer_type',
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='is_preposition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='is_verb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancyquestion',
            name='is_preposition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancyquestion',
            name='is_verb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='text',
            name='level',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
