# Generated by Django 2.1.7 on 2019-12-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0004_auto_20191208_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='qauser',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
