# Generated by Django 2.1.7 on 2019-11-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0004_auto_20191112_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('verb_id', models.IntegerField()),
            ],
        ),
    ]
