# Generated by Django 2.1.7 on 2019-11-15 15:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('language_skills', '0005_preposition_verb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacancyQuestion',
            new_name='BlankQuestion',
        ),
        migrations.RenameModel(
            old_name='VacancyQuestionSet',
            new_name='BlankQuestionSet',
        ),
        migrations.RenameModel(
            old_name='SelectedVacancyQuestion',
            new_name='SelectedBlankQuestion',
        ),
    ]
