# Generated by Django 2.1.7 on 2019-12-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0005_qauser_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlankQuestionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosine_similarity', models.FloatField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userblankquestionrelation', to='language_skills.BlankQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userblankquestionrelation', to='language_skills.QAUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserMCQuestionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosine_similarity', models.FloatField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermcquestionrelation', to='language_skills.MultipleChoiceQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermcquestionrelation', to='language_skills.QAUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='userquestionrelation',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionrelation',
            name='user',
        ),
        migrations.AlterField(
            model_name='blankquestionset',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='blankquestionset', to='language_skills.SelectedBlankQuestion'),
        ),
        migrations.AlterField(
            model_name='mcquestionset',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='mcquestionset', to='language_skills.SelectedMCQuestion'),
        ),
        migrations.AlterField(
            model_name='selectedblankquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedblankquestion', to='language_skills.BlankQuestion'),
        ),
        migrations.AlterField(
            model_name='selectedmcquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedmcquestion', to='language_skills.MultipleChoiceQuestion'),
        ),
        migrations.DeleteModel(
            name='UserQuestionRelation',
        ),
    ]
