# Generated by Django 2.1.7 on 2019-12-03 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0006_auto_20191115_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0)),
                ('question', models.ManyToManyField(to='language_skills.BlankQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='qauser',
            name='birth_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='is_knowing_persian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qauser',
            name='is_parent_persian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qauser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qauser',
            name='lang_reason',
            field=models.CharField(blank=True, choices=[(1, 'تحصیل دانشجوی خارجی در ایران'), (2, 'اختلال در یادگیری زبان فارسی'), (3, 'ایرانی مقیم خارج از کشور'), (4, 'علاقه شخصی')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='major',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='native_lang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='persian_knowing_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userquestionrelation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language_skills.QAUser'),
        ),
    ]
