# Generated by Django 2.1.7 on 2019-12-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0006_auto_20191208_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestionset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
