# Generated by Django 2.1.7 on 2019-12-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0007_mcquestionset_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankquestionset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
