# Generated by Django 2.1.7 on 2019-12-03 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0007_auto_20191203_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qauser',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
