# Generated by Django 2.1.7 on 2019-12-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0008_auto_20191203_1758'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='qauser',
        #     name='birth_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
