# Generated by Django 2.1.7 on 2019-12-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0009_auto_20191204_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VerbInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=100)),
                ('past_root', models.CharField(max_length=100)),
                ('passive', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Verb',
        ),
        migrations.AddField(
            model_name='verbform',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_skills.VerbInfo'),
        ),
    ]
