# Generated by Django 2.1.7 on 2019-12-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0010_auto_20191204_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qauser',
            name='birth_date',
        ),
    ]
