# Generated by Django 2.1.7 on 2020-01-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0010_textwriting'),
    ]

    operations = [
        migrations.AddField(
            model_name='textwriting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_text_writing', to='language_skills.QAUser'),
        ),
    ]
