# Generated by Django 2.1.7 on 2019-12-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0011_remove_qauser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qauser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
