# Generated by Django 2.1.7 on 2020-01-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0011_textwriting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admins', models.ManyToManyField(blank=True, related_name='qagroup_admins', to='language_skills.QAUser')),
                ('users', models.ManyToManyField(blank=True, related_name='qagroup_users', to='language_skills.QAUser')),
            ],
        ),
    ]
