# Generated by Django 2.1.7 on 2020-02-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0012_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='qauser',
            name='activation_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qauser',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
