# Generated by Django 2.1.7 on 2020-02-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0013_auto_20200207_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qauser',
            old_name='activation_link',
            new_name='activation_token',
        ),
    ]
