# Generated by Django 2.1.7 on 2020-03-23 22:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('language_skills', '0015_blocked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='QAGroup',
        ),
        migrations.RemoveField(
            model_name='mcquestionhistory',
            name='question',
        ),
        migrations.DeleteModel(
            name='MCQuestionHistory',
        ),
    ]
