# Generated by Django 2.1.7 on 2020-04-23 12:57

from django.db import migrations, models


def fill_kind_field_func(apps, schema_editor):
    blank_questions = apps.get_model('language_skills', 'BlankQuestion')
    for q in blank_questions.objects.all():
        q.kind = 'verb' if q.is_verb else 'prep'
        q.save()
    mc_questions = apps.get_model('language_skills', 'MultipleChoiceQuestion')
    for q in mc_questions.objects.all():
        q.kind = 'verb' if q.is_verb else 'prep'
        q.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0016_auto_20200323_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankquestion',
            name='kind',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='kind',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(fill_kind_field_func),
        migrations.RemoveField(
            model_name='blankquestion',
            name='is_preposition',
        ),
        migrations.RemoveField(
            model_name='blankquestion',
            name='is_verb',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='is_preposition',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='is_verb',
        ),
    ]
