# Generated by Django 2.1.1 on 2020-04-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0017_auto_20200423_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('randommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='language_skills.RandomModel')),
                ('text', models.CharField(max_length=100)),
                ('root', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
            bases=('language_skills.randommodel',),
        ),
        migrations.CreateModel(
            name='Advreb',
            fields=[
                ('randommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='language_skills.RandomModel')),
                ('text', models.CharField(max_length=100)),
                ('root', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
            bases=('language_skills.randommodel',),
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('randommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='language_skills.RandomModel')),
                ('text', models.CharField(max_length=100)),
                ('root', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
            bases=('language_skills.randommodel',),
        ),
        migrations.CreateModel(
            name='Conjunction',
            fields=[
                ('randommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='language_skills.RandomModel')),
                ('text', models.CharField(max_length=100)),
                ('root', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
            bases=('language_skills.randommodel',),
        ),
        migrations.CreateModel(
            name='Determiner',
            fields=[
                ('randommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='language_skills.RandomModel')),
                ('text', models.CharField(max_length=100)),
                ('root', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
            bases=('language_skills.randommodel',),
        ),
        migrations.CreateModel(
            name='Interjection',
            fields=[
                ('randommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='language_skills.RandomModel')),
                ('text', models.CharField(max_length=100)),
                ('root', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
            bases=('language_skills.randommodel',),
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('randommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='language_skills.RandomModel')),
                ('text', models.CharField(max_length=100)),
                ('root', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
            bases=('language_skills.randommodel',),
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('randommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='language_skills.RandomModel')),
                ('text', models.CharField(max_length=100)),
                ('root', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
            bases=('language_skills.randommodel',),
        ),
    ]
