# Generated by Django 2.1.1 on 2020-04-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0018_adjective_advreb_classifier_conjunction_determiner_interjection_noun_pronoun_randommodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advreb',
            new_name='Adverb',
        ),
    ]
