# Generated by Django 2.1.1 on 2020-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_skills', '0019_auto_20200424_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankquestion',
            name='part_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='part_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
